import type { SandpiPreferences } from "./types";

export type OperationLanguage = SandpiPreferences["general"]["language"];
export type SendShortcut = SandpiPreferences["general"]["sendShortcut"];

export interface ComposerKeyInput {
  key: string;
  shiftKey: boolean;
  metaKey: boolean;
  ctrlKey: boolean;
  isComposing: boolean;
}

export function shouldSubmitComposer(
  input: ComposerKeyInput,
  shortcut: SendShortcut,
) {
  if (input.key !== "Enter" || input.isComposing || input.shiftKey) {
    return false;
  }

  if (shortcut === "mod-enter") {
    return input.metaKey || input.ctrlKey;
  }

  return true;
}

const copy = {
  en: {
    sidebar: {
      navigation: "Sandpi navigation",
      collapse: "Collapse sidebar",
      close: "Close navigation",
      newEnvironment: "New environment",
      searchSessions: "Search sessions",
      environments: "Environments",
      newSession: "New session",
      newSessionIn: (name: string) => `New session in ${name}`,
      environmentSettings: "Environment settings",
      environmentSettingsFor: (name: string) => `${name} settings`,
      pinned: "Pinned",
      showMoreSessions: (count: number) => `Show ${count} more`,
      showMoreSessionsIn: (count: number, name: string) =>
        `Show ${count} more sessions in ${name}`,
      showFewerSessions: "Show fewer",
      showFewerSessionsIn: (name: string) =>
        `Show fewer sessions in ${name}`,
      renameSession: (title: string) => `Rename ${title}`,
      sessionActions: (title: string) => `Session actions for ${title}`,
      actionsFor: (title: string) => `Actions for ${title}`,
      forkSession: "Fork session",
      unpin: "Unpin",
      pin: "Pin",
      rename: "Rename",
      archive: "Archive",
      preferences: "Preferences",
      help: "Help & feedback",
      logout: "Log out",
      loggingOut: "Logging out…",
      logoutFailed: "Sandpi could not log you out. Try again.",
      accountMenu: "Open account menu",
      closeAccountMenu: "Close account menu",
      accountActions: "Account actions",
      githubRepository: "Sandpi GitHub repository",
      nativeAppsComingSoon:
        "iOS · Android · HarmonyOS · Windows · macOS coming soon",
      billingUsage: "Billing & usage",
      sandboxRuntime: "Sandbox runtime",
      loadingUsage: "Loading usage…",
      usageUnavailable: "Usage unavailable",
      unlimitedRuntime: "Unlimited allowance",
      gibHours: "GiB-hours",
      gibHoursUsed: "GiB-hours used",
    },
    guest: {
      signInOrSignUp: "Log in or sign up",
      signInContext: "Continue to your workspace",
      emptySidebar: "Log in to see your Environments and Sessions.",
      expandSidebar: "Expand sidebar",
      openNavigation: "Open navigation",
      newSession: "New session",
      ready: "Ready when you are",
      question: "What should Codex work on?",
      introduction:
        "Describe the task first. Sandpi asks you to log in only when you send it.",
      persistentWorkspace: "Persistent workspace",
      secureSandbox: "Secure Sandbox",
      backgroundWork: "Keeps working",
      placeholder: "Ask Codex to work on something…",
      signedOut: "Log in on send",
      send: "Send message and continue",
      starterLabel: "Starter instructions",
      starters: [
        "Inspect this workspace and explain its structure",
        "Find the highest-risk bug and fix it",
        "Run the tests and resolve any failures",
      ],
    },
    helpFeedback: {
      eyebrow: "Support",
      title: "Help & feedback",
      description:
        "Find Sandpi documentation, report a problem, or tell us what would make the workspace better.",
      documentation: "Read the documentation",
      documentationDescription:
        "Learn how Environments, Sessions, Sandboxes, Skills, and MCP work.",
      reportBug: "Report a problem",
      reportBugDescription:
        "Open a prefilled GitHub issue with safe browser context.",
      shareFeedback: "Share feedback",
      shareFeedbackDescription:
        "Suggest an improvement or describe a workflow Sandpi should support.",
      publicIssueNotice:
        "GitHub issues are public. Do not include credentials, private code, or customer data.",
      close: "Close Help & feedback",
      opensNewTab: "Opens in a new tab",
    },
    inspector: {
      label: "Environment inspector",
      views: "Inspector views",
      files: "Files",
      browser: "Browser",
      metrics: "Metrics",
      settings: "Settings",
      openEnvironmentSettings: "Open Environment settings",
      close: "Close inspector",
      resize: "Resize Inspector",
      resizeValue: (percent: number) => `${percent}% of the workspace`,
      resizeHelp: "Drag to resize Inspector. Double-click to reset.",
      loadingView: (view: string) => `Loading ${view.toLowerCase()}…`,
      browserTitle: "Shared Environment browser",
      browserStarting: "Starting the shared Environment browser…",
      browserUnavailable:
        "The shared Environment browser did not become ready. Retry after the Environment finishes resuming.",
      browserRetry: "Retry",
      browserTabs: "Browser tabs",
      browserNewTab: "New tab",
      browserCloseTab: (title: string) => `Close ${title}`,
      browserUntitledTab: "New tab",
      browserLoading: "Loading…",
      browserViewport: "Browser viewport",
      browserViewportDesktop: "Desktop fit",
      browserViewportResponsive: "Responsive",
      browserViewportMobile: "Mobile",
      workspaceFiles: "Workspace files",
      openNewView: "Open in Sandpi Cloud IDE (coming later)",
      binaryFilePreview: "Binary files cannot be previewed here.",
      volumeLive: (volumeId: string) => `Volume live · ${volumeId}`,
      lastHour: "Last hour",
      last15Minutes: "Last 15 minutes",
      last6Hours: "Last 6 hours",
      last24Hours: "Last 24 hours",
      last7Days: "Last 7 days",
      runtimeMetrics: "Runtime metrics",
      metricsRange: "Metrics time range",
      fifteenMinutes: "15 minutes",
      oneHour: "1 hour",
      sixHours: "6 hours",
      twentyFourHours: "24 hours",
      sevenDays: "7 days",
      metricChart: "Metric values over the selected range",
      metricChartInstructions:
        "Hover to inspect a sample. With the chart focused, use the left and right arrow keys to move between samples. Shaded bands mark Sandpi-managed Sandbox pauses.",
      metricSeries: "Metric series",
      showMetricSeries: (label: string) => `Show ${label}`,
      hideMetricSeries: (label: string) => `Hide ${label}`,
      idlePause: "Sandpi-managed pause",
      average: (value: number) => `avg ${value}%`,
      peak: (value: number) => `peak ${value}%`,
      memory: "Memory",
      networkTraffic: "Network traffic",
      received: "Received",
      sent: "Sent",
      percentOfLimit: (value: number) => `${value}% of limit`,
      memoryLimit: (value: number) => `${value} GiB limit`,
      sandbox: "Sandbox",
      supervisorSession: "Supervisor session",
      runtimeGeneration: "Runtime generation",
      metricsBoundary:
        "Chart-ready runtime series from Sandbox0 observability. Billing and metering remain a separate usage-truth path.",
    },
  },
  "zh-CN": {
    sidebar: {
      navigation: "Sandpi 导航",
      collapse: "收起侧边栏",
      close: "关闭导航",
      newEnvironment: "新建环境",
      searchSessions: "搜索会话",
      environments: "环境",
      newSession: "新建会话",
      newSessionIn: (name: string) => `在 ${name} 中新建会话`,
      environmentSettings: "环境设置",
      environmentSettingsFor: (name: string) => `${name} 设置`,
      pinned: "已置顶",
      showMoreSessions: (count: number) => `再显示 ${count} 条`,
      showMoreSessionsIn: (count: number, name: string) =>
        `在 ${name} 中再显示 ${count} 条 Session`,
      showFewerSessions: "收起",
      showFewerSessionsIn: (name: string) => `收起 ${name} 的 Session 列表`,
      renameSession: (title: string) => `重命名 ${title}`,
      sessionActions: (title: string) => `${title} 的会话操作`,
      actionsFor: (title: string) => `${title} 的操作`,
      forkSession: "派生会话",
      unpin: "取消置顶",
      pin: "置顶",
      rename: "重命名",
      archive: "归档",
      preferences: "偏好设置",
      help: "帮助与反馈",
      logout: "退出登录",
      loggingOut: "正在退出…",
      logoutFailed: "无法退出登录，请重试。",
      accountMenu: "打开账户菜单",
      closeAccountMenu: "关闭账户菜单",
      accountActions: "账户操作",
      githubRepository: "Sandpi GitHub 仓库",
      nativeAppsComingSoon:
        "iOS · Android · HarmonyOS · Windows · macOS 即将发布",
      billingUsage: "订阅与用量",
      sandboxRuntime: "Sandbox 运行用量",
      loadingUsage: "正在加载用量…",
      usageUnavailable: "用量暂不可用",
      unlimitedRuntime: "不限额度",
      gibHours: "GiB 小时",
      gibHoursUsed: "GiB 小时已用",
    },
    guest: {
      signInOrSignUp: "登录或注册",
      signInContext: "继续进入你的工作区",
      emptySidebar: "登录后查看你的环境和会话。",
      expandSidebar: "展开侧边栏",
      openNavigation: "打开导航",
      newSession: "新建会话",
      ready: "随时可以开始",
      question: "想让 Codex 做什么？",
      introduction: "可以先描述任务，真正发送时 Sandpi 才会请你登录。",
      persistentWorkspace: "持久工作区",
      secureSandbox: "安全 Sandbox",
      backgroundWork: "持续运行",
      placeholder: "让 Codex 执行一个任务…",
      signedOut: "发送时登录",
      send: "发送消息并继续",
      starterLabel: "示例任务",
      starters: [
        "检查这个工作区并解释其结构",
        "找出风险最高的问题并修复",
        "运行测试并解决所有失败",
      ],
    },
    helpFeedback: {
      eyebrow: "支持",
      title: "帮助与反馈",
      description:
        "查看 Sandpi 文档、报告问题，或者告诉我们怎样让工作区更好用。",
      documentation: "查看文档",
      documentationDescription:
        "了解环境、会话、Sandbox、Skills 和 MCP 的工作方式。",
      reportBug: "报告问题",
      reportBugDescription: "使用安全的浏览器上下文创建 GitHub Issue。",
      shareFeedback: "提交建议",
      shareFeedbackDescription:
        "建议一项改进，或者描述希望 Sandpi 支持的工作流。",
      publicIssueNotice:
        "GitHub Issue 是公开的，请勿包含凭证、私有代码或客户数据。",
      close: "关闭帮助与反馈",
      opensNewTab: "将在新标签页打开",
    },
    inspector: {
      label: "环境检查器",
      views: "检查器视图",
      files: "文件",
      browser: "Browser",
      metrics: "指标",
      settings: "设置",
      openEnvironmentSettings: "打开 Environment 设置",
      close: "关闭检查器",
      resize: "调整检查器宽度",
      resizeValue: (percent: number) => `占工作区 ${percent}%`,
      resizeHelp: "拖动以调整检查器宽度，双击恢复默认比例。",
      loadingView: (view: string) => `正在加载${view}…`,
      browserTitle: "共享 Environment 浏览器",
      browserStarting: "正在启动共享 Environment 浏览器…",
      browserUnavailable:
        "共享 Environment 浏览器未能就绪，请等待 Environment 恢复完成后重试。",
      browserRetry: "重试",
      browserTabs: "浏览器标签页",
      browserNewTab: "新建标签页",
      browserCloseTab: (title: string) => `关闭 ${title}`,
      browserUntitledTab: "新标签页",
      browserLoading: "正在加载…",
      browserViewport: "浏览器视口",
      browserViewportDesktop: "桌面自适应",
      browserViewportResponsive: "响应式",
      browserViewportMobile: "移动端",
      workspaceFiles: "Workspace 文件",
      openNewView: "在 Sandpi Cloud IDE 中打开（后续支持）",
      binaryFilePreview: "暂不支持在这里预览二进制文件。",
      volumeLive: (volumeId: string) => `Volume 在线 · ${volumeId}`,
      lastHour: "最近一小时",
      last15Minutes: "最近 15 分钟",
      last6Hours: "最近 6 小时",
      last24Hours: "最近 24 小时",
      last7Days: "最近 7 天",
      runtimeMetrics: "运行时指标",
      metricsRange: "指标时间范围",
      fifteenMinutes: "15 分钟",
      oneHour: "1 小时",
      sixHours: "6 小时",
      twentyFourHours: "24 小时",
      sevenDays: "7 天",
      metricChart: "所选时间范围内的指标值",
      metricChartInstructions:
        "悬浮可查看采样点；聚焦图表后，可使用左右方向键切换采样点。阴影区域表示 Sandpi 管理的 Sandbox 暂停。",
      metricSeries: "指标序列",
      showMetricSeries: (label: string) => `显示${label}`,
      hideMetricSeries: (label: string) => `隐藏${label}`,
      idlePause: "Sandpi 管理的暂停",
      average: (value: number) => `平均 ${value}%`,
      peak: (value: number) => `峰值 ${value}%`,
      memory: "内存",
      networkTraffic: "网络流量",
      received: "接收",
      sent: "发送",
      percentOfLimit: (value: number) => `占上限 ${value}%`,
      memoryLimit: (value: number) => `上限 ${value} GiB`,
      sandbox: "Sandbox",
      supervisorSession: "Supervisor Session",
      runtimeGeneration: "运行时世代",
      metricsBoundary:
        "运行时序列来自 Sandbox0 可观测性数据。Billing 与 metering 仍使用独立的用量事实链路。",
    },
  },
} as const;

export function getOperationUiCopy(language: OperationLanguage) {
  return copy[language];
}
