import type { OperationLanguage } from "@/lib/operation-ui";
import type { SessionStatus } from "@/lib/types";

const copy = {
  en: {
    conversation: {
      label: "Codex conversation",
      expandSidebar: "Expand sidebar",
      openNavigation: "Open navigation",
      status: (status: SessionStatus) =>
        status === "running"
          ? "Running"
          : status === "waiting"
            ? "Waiting"
            : status === "paused"
              ? "Paused"
              : "Completed",
      environmentRevision: (revision: number) => `Environment r${revision}`,
      terminal: "Terminal",
      closeInspector: "Close inspector",
      openInspector: "Open inspector",
      moreSessionActions: "More session actions",
      you: "You",
      openFile: "Open file",
      copyResponse: "Copy response",
      copy: "Copy",
      confirmDelete: "Confirm delete",
      deleteFromHere: "Delete from here?",
      delete: "Delete",
      cancelDelete: "Cancel delete",
      cancel: "Cancel",
      editMessage: "Edit message",
      editFromHere: "Edit from here",
      forkTurnMessage: "Fork Codex turn from message",
      forkTurnHere: "Fork Codex turn from here",
      copyMessage: "Copy message",
      deleteMessage: "Delete message",
      editing: "Editing from this message",
      descendantsHidden: "This Codex turn and later turns are hidden",
      cancelEditing: "Cancel editing",
      messageAgent: (agent: string) => `Message ${agent}`,
      editPlaceholder: "Edit this instruction…",
      askPlaceholder: (agent: string) => `Ask ${agent} to work in this session…`,
      selectModel: (agent: string) => `Select ${agent} model`,
      attachFile: "Attach file",
      mentionFile: "Mention file",
      attachedImages: "Attached images",
      removeImage: (name: string) => `Remove ${name}`,
      imageLimit: (count: number) => `Up to ${count} images per message.`,
      imageTooLarge: "Each image must be 10 MB or smaller.",
      imagePasteFailed: "Could not read that clipboard image.",
      boundToEnvironment: "Bound to this Environment",
      environment: "Environment",
      durableSession: "Durable session",
      sendMessage: "Send message",
      workingInWorkspace: "Working in /workspace",
      networkInherited: (name: string) => `Network policy inherited from ${name}`,
    },
    newSession: {
      expandSidebar: "Expand sidebar",
      openNavigation: "Open navigation",
      title: "New session",
      readyToFork: (revision: number) => `Ready to fork Environment r${revision}`,
      environmentSettings: (name: string) => `${name} settings`,
      question: (agent: string) => `What should ${agent} work on?`,
      introduction: (environment: string) =>
        `The first instruction creates an isolated Sandbox from ${environment} and starts its Codex app-server thread.`,
      environmentRevision: (revision: number) => `Environment r${revision}`,
      agentBound: (agent: string) => `${agent} bound`,
      hardTtl: "30-day hard TTL",
      emptyInstruction: (agent: string) => `Tell ${agent} what to work on.`,
      startFailed: "Could not start the Session. Try again.",
      placeholder: (agent: string) => `Ask ${agent} to work on something…`,
      selectModel: (agent: string) => `Select ${agent} model`,
      attachFile: "Attach file",
      mentionFile: "Mention file",
      environment: "Environment",
      starting: "Starting Session",
      sendAndStart: "Send instruction and start Session",
      starterLabel: "Starter instructions",
      starters: [
        "Inspect this workspace and explain its structure",
        "Find the highest-risk bug and fix it",
        "Run the tests and resolve any failures",
      ],
    },
  },
  "zh-CN": {
    conversation: {
      label: "Codex 对话",
      expandSidebar: "展开侧边栏",
      openNavigation: "打开导航",
      status: (status: SessionStatus) =>
        status === "running"
          ? "运行中"
          : status === "waiting"
            ? "等待中"
            : status === "paused"
              ? "已暂停"
              : "已完成",
      environmentRevision: (revision: number) => `环境 r${revision}`,
      terminal: "终端",
      closeInspector: "关闭检查器",
      openInspector: "打开检查器",
      moreSessionActions: "更多会话操作",
      you: "你",
      openFile: "打开文件",
      copyResponse: "复制回复",
      copy: "复制",
      confirmDelete: "确认删除",
      deleteFromHere: "从这里开始删除？",
      delete: "删除",
      cancelDelete: "取消删除",
      cancel: "取消",
      editMessage: "编辑消息",
      editFromHere: "从这里开始编辑",
      forkTurnMessage: "从消息派生 Codex Turn",
      forkTurnHere: "从这里派生 Codex Turn",
      copyMessage: "复制消息",
      deleteMessage: "删除消息",
      editing: "正在从这条消息编辑",
      descendantsHidden: "当前 Codex Turn 及后续 Turn 已隐藏",
      cancelEditing: "取消编辑",
      messageAgent: (agent: string) => `向 ${agent} 发送消息`,
      editPlaceholder: "编辑这条指令…",
      askPlaceholder: (agent: string) => `让 ${agent} 在此会话中执行任务…`,
      selectModel: (agent: string) => `选择 ${agent} 模型`,
      attachFile: "附加文件",
      mentionFile: "引用文件",
      attachedImages: "已附加图片",
      removeImage: (name: string) => `移除 ${name}`,
      imageLimit: (count: number) => `每条消息最多添加 ${count} 张图片。`,
      imageTooLarge: "每张图片不能超过 10 MB。",
      imagePasteFailed: "无法读取剪贴板中的图片。",
      boundToEnvironment: "绑定到此环境",
      environment: "环境",
      durableSession: "持久会话",
      sendMessage: "发送消息",
      workingInWorkspace: "工作目录 /workspace",
      networkInherited: (name: string) => `网络策略继承自 ${name}`,
    },
    newSession: {
      expandSidebar: "展开侧边栏",
      openNavigation: "打开导航",
      title: "新建会话",
      readyToFork: (revision: number) => `已准备从环境 r${revision} 派生`,
      environmentSettings: (name: string) => `${name} 设置`,
      question: (agent: string) => `希望 ${agent} 做什么？`,
      introduction: (environment: string) =>
        `第一条指令会从 ${environment} 创建隔离的 Sandbox，并启动 Codex app-server Thread。`,
      environmentRevision: (revision: number) => `环境 r${revision}`,
      agentBound: (agent: string) => `已绑定 ${agent}`,
      hardTtl: "30 天硬性 TTL",
      emptyInstruction: (agent: string) => `请告诉 ${agent} 要完成什么任务。`,
      startFailed: "无法启动会话，请重试。",
      placeholder: (agent: string) => `让 ${agent} 执行任务…`,
      selectModel: (agent: string) => `选择 ${agent} 模型`,
      attachFile: "附加文件",
      mentionFile: "引用文件",
      environment: "环境",
      starting: "正在启动会话",
      sendAndStart: "发送指令并启动会话",
      starterLabel: "入门指令",
      starters: [
        "检查此工作区并说明其结构",
        "找出风险最高的缺陷并修复",
        "运行测试并解决所有失败",
      ],
    },
  },
} as const;

export function getCodexUiCopy(language: OperationLanguage) {
  return copy[language];
}
